### ISSUE TITLE
Update gulp-kit to support gulp 4.0.0

### ISSUE THREAD

**Issue by bennyjien** [Lukx/gulp-kit#15]
I cannot run gulp-kit in gulp 4.0.0, I think it has issue with outdated gulp-util. Could someone help me with this?

**Comment by fatso83** [comment]
Hi, Benny. I am sorry that this just went into a black hole. I had just set notifications to "Participating", which means I never got the notifications about new PRs or issues. For years :see_no_evil: 

Probably not an issue for you longer, but this has been fixed in v1.0. Hope you got your issue sorted ...
