### ISSUE TITLE
ReferenceError: gutil is not defined

### ISSUE THREAD

**Issue by racha** [Lukx/gulp-kit#21]
ReferenceError: gutil is not defined

Can we get a fix for this which has been an issue since you updated to 1.0.0 ?

**Comment by fatso83** [comment]
Can you provide a PR? Probably quite a quick fix, I would assume, seeing that you know what it is. Been a while :sweat_smile:

**Comment by fatso83** [comment]
I fixed the error in the stuff I just pushed to `master`, but I could not for the life of me figure out where result ended up. It has been too longs since I used Gulp ... and I have work to do. If you can check out the repo and maybe update the example in the README (or test/integration-test.js) I can push a new version to NPM.
